# Generated by Django 3.0.2 on 2020-02-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
