# Generated by Django 3.0.2 on 2020-02-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
