# Generated by Django 3.0.2 on 2020-02-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_checkoutaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CheckoutAddress'),
        ),
    ]
